### ISSUE TITLE
Add support for http://pasty.link/ and http://issuu-downloader.abuouday.com/

### ISSUE THREAD

**Issue by jaredbidlow** [dsohler/oneclick-downloader#1]

**Comment by dsohler** [comment]
Added and successfully tested Issuu PDF Downloader in 29685e1. Can you please provide more information about pasty.link and where it’s used?

I’ll release the Chrome/Chromium extension in the store as soon as this issue is solved as a whole.

**Comment by jaredbidlow** [comment]
because you added issuu downloader (haven't tested yet) I have no need for pasty link. Thanks

**Comment by dsohler** [comment]
Uploaded new version to store with version *1.1.4 2015-11-17*. Will be available for updating as soon as Google processed it.
