### ISSUE TITLE
Bug with URL encoding

### ISSUE THREAD

**Issue by GitBoudewijn** [dsohler/oneclick-downloader#2]
Hey,

Thanks for the great extension. It works really well. I did however find a bug.

Take this link for example:
http://www.imagebam.com/image/2981e7508976444
If you download it with Chrome the normal way it will save it as **A (1).jpg**, however if you download it with One-Click Downloader it will save it as **A%20%281%29.jpg**.

Hope you can fix this.
Thanks!

Edit: I used the url code wrong, link should work now.

**Comment by dsohler** [comment]
Thanks for the report. I’ll investigate and will release an updated definition basing on your example link.

**Comment by GitBoudewijn** [comment]
Thanks for the response.

Do you think this issue is specific to the Imagebam definition, or will it occur with any link that uses URL encoding? I'll try to find a link from another host.

**Comment by dsohler** [comment]
This should affect all definitions where the file name is determined by simply taking the `<img>` tag's `src` value when this value contains anything that was urlencoded.

The actual downloading/storage mechanism doesn't alter the path nor the file name in general. All that is done with the returned file name is [replacing "critical characters" with a `-` sign](https://github.com/dsohler/oneclick-downloader/blob/master/oneclick-downloader/downloader/download.js#L53).

**Comment by GitBoudewijn** [comment]
Hmm right. So apparently when you let Chrome determine the filename it decodes the url, but when you specify a filename yourself it uses that.
https://developer.chrome.com/extensions/downloads#method-download
Weird thing is that **filename** is actually not just the name but also the path, otherwise you could just leave it blank.
Don't know what the best solution is.

**Comment by dsohler** [comment]
Fixed by extension in a5bb927. See detailed description there for solution.

I don’t know if that is the cleanest solution. But my approach is to alter the result of the definitions as less as possible to give highest grade of flexibility to definition authors. Let authors decide to apply the decoding of the file name to me is the *nicest* solution when having authors in mind.
