### ISSUE TITLE
Instagram downloading broken?

### ISSUE THREAD

**Issue by GitBoudewijn** [dsohler/oneclick-downloader#4]
When you go to an Instagram profile and use the extension it recognizes the links on the page, however when you try to download them nothing happens and the Processed Links page remains empty.

**Comment by dsohler** [comment]
Seems like they changed their code. I’ll investigate as soon as possible and will release a definitions update. Thanks for the report

**Comment by dsohler** [comment]
Fixed in 54d1311 by using `og:image` which seems to be the full-size image. This is way more robust and super easy to parse. Plus: this meta value should remain the same regardless of what they change on the site so there should no further breakage except they change or remove `og:image`.
