### ISSUE TITLE
Flickr duplicate images

### ISSUE THREAD

**Issue by GitBoudewijn** [dsohler/oneclick-downloader#5]
One more bug:

When you download from a Flickr photostream or album it lists each image twice, the second time with #comments added to the link.

For example:
https://www.flickr.com/photos/pinks2000

Gives:
- https://www.flickr.com/photos/pinks2000/30174998521/
- https://www.flickr.com/photos/pinks2000/30174998521/#comments
- https://www.flickr.com/photos/pinks2000/29467570624/
- https://www.flickr.com/photos/pinks2000/29467570624/#comments
- https://www.flickr.com/photos/pinks2000/29957146196/
- https://www.flickr.com/photos/pinks2000/29957146196/#comments
- ...

**Comment by dsohler** [comment]
Thanks for all the feedback! I wasn't able to work on this since a few months now. I plan a definitions update as soon as possible and will investigate on this one, too.

**Comment by dsohler** [comment]
Fixed in 0022982 (see detailed description for potential issues with this fix). Fixed version will be available with the next definitions update.
