### ISSUE TITLE
Couple of requests

### ISSUE THREAD

**Issue by GitBoudewijn** [dsohler/oneclick-downloader#7]
Hey,

I have a couple of requests for definitions if you have the time:

**Hotflick (hotflick.net)**
Example:
http://forums.superiorpics.com/ubbthreads/ubbthreads.php/topics/1065500/ADDS_Mary_Elizabeth_Winstead_S

**SomeImage (someimage.com)**
Example (mixed with Imagebam):
http://www.carreck.com/pictures/2016/07/02/maryelizabethwinstead-candids-fragrancefoundation-nyc-jun-7th-2016/

**Reddit (i.redd.it/i.reddituploads.com)**
Example (mixed with Imgur):
https://www.reddit.com/r/gentlemanboners/

**Instagram videos**
It would be nice if you can download videos from Instagram as well as photos.

**Comment by GitBoudewijn** [comment]
By the way it might also be smart to also support image boards like 4chan.org and 8ch.net. Will probably increase the number of people that find your extension.:)

**Comment by dsohler** [comment]
hotflick.net added in ebc6a03 and someimage.com added in c311c1a. The update will be pushed to the store when the milestone is reached.

For the direct uploads to Reddit which uses i.redd.it and i.reddituploads.com it seems like that the images are only shown within the actual post and there seems no way to programmatically detect them when in the posts overview by just getting the links from the page.

Can you provide some examples for Instagram videos?

**Comment by GitBoudewijn** [comment]
Thanks!

i.reddituploads.com should be easy since it's just a direct link. But you're right that there's no way to distinguish between an i.redd.it post and a self post (except that it has i.redd.it next to the link). Maybe you could just match all Reddit posts, since most subreddits with images don't allow self posts anyway.

https://www.instagram.com/instagram/
The first and third posts are videos. When you try to download them now it just downloads the preview images.

http://boards.4chan.org/w/thread/1965115/persona-thread
http://8ch.net/pone/res/268202.html
And here are examples of a 4chan and 8chan thread. They all have just direct links to images. Would it be a good idea to have a catch all for direct links? Basically any link that ends with **.jpg** or **.png** and doesn't have a **?** somewhere in it. This way you wouldn't have to add definitions for each individual domain.

**Comment by dsohler** [comment]
Added exceptional video downloading for Instagram with commit 563b1d4.

Added reddituploads.com in 89108a6. Matching generally all reddit posts would cause way too many false positives on Subreddits that allow all kinds of posts.

Adding a general function that simply downloads what’s found in the href attribute is absolutely possible. The only problem would be the identifying of the link to use this function. The extension is built around individual one-click hosting sites and it would need some significant changes to the core functionality to add “generic” downloading functions.

Adding the top most relevant image boards would be easy. They could even share the same function when all of them provide simple direct links to images. But currently adding matchers and functions that are too generic is simply not possible.

**Comment by GitBoudewijn** [comment]
You're right that you would get false positives but my reasoning was that the subreddits that you would want to download from consist exclusively of image posts anyway, so it wouldn't matter as much. But maybe you could have an option to enable "experimental" definitions or something like that, for people who want functionality rather than reliability. (More options is always a good solution.:P)

The way I envisioned it to work is that it would get a list of all the links, match all the direct links, then take the remainder and match those to the definitions.

**Comment by dsohler** [comment]
I’m still thinking of a good way to implement *custom hosters* so people can add whatever they want (there will be only very little error checking so people might be able to destroy the universe :joy:). But that’s definitely a long-term thing to implement. The options page for it already exists.

**Comment by GitBoudewijn** [comment]
Yeah that's definitely a good idea. Would be cool if it had a wizard interface so your grandma could use it.:P But since you've implemented the majority of my requests I'll close this issue now and maybe make a new one for other things.
