### ISSUE TITLE
Small Imagevenue bug

### ISSUE THREAD

**Issue by GitBoudewijn** [dsohler/oneclick-downloader#9]
Found another bug!

When downloading from Imagevenue, it removes the leading and trailing numbers from the filename. However, when the file extension is capitalized (.JPG) it doesn't. (Personally I wouldn't mind if it always saves it with the file extension in lowercase.)

Edit:
Lowercase example:
http://img250.imagevenue.com/img.php?image=10714_Olivia_Wilde_Rush_Premiere_London_J0001_014_122_538lo.jpg
Uppercase example:
http://img285.imagevenue.com/img.php?image=10744_Olivia_Wilde_Rush_Premiere_London_J0001_025_122_532lo.JPG

**Comment by dsohler** [comment]
Confirmed and fixed in f140d48. The suffix will be untouched but now the additional stuff added bei IV will be removed regardless of how the suffix or “lo ID” is capitalized.

I will push it to the market as soon as the milestone is closed and all definitions are fixed/added.
